### ISSUE TITLE
OpenOCD sometimes drops the GDB connection (GD32VF103C-START)

### ISSUE THREAD

**Issue by kristofmulier** [GigaDevice-Semiconductor/openocd#3]
> Note: I've tried on both `Windows10` and `Ubuntu 20.04.1 LTS`. The errors described below are the same on both systems.

I'm trying to connect `riscv-none-embed-gdb` - which is part of the xPack RISC-V toolchain - to OpenOCD. For this test, I'm using the double-console-approach: I launch OpenOCD in one console and GDB in another.

This is how I launch OpenOCD such that it connects to the MCU on the `GD32VF103C-START` board:

```
$ openocd -f openocd_probe.cfg -f openocd_chip.cfg -c "init; reset halt;"

    xPack OpenOCD, x86_64 Open On-Chip Debugger 0.10.0+dev-00003-gfa63b9ee9 (2020-11-19-15:34)
    Licensed under GNU GPL v2
    For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
    jtag
    Info : CMSIS-DAP: SWD  Supported
    Info : CMSIS-DAP: JTAG Supported
    Info : CMSIS-DAP: FW Version = 2.0.0
    Info : CMSIS-DAP: Interface Initialised (JTAG)
    Info : SWCLK/TCK = 1 SWDIO/TMS = 1 TDI = 1 TDO = 0 nTRST = 0 nRESET = 1
    Info : CMSIS-DAP: Interface ready
    Info : clock speed 1000 kHz
    Info : cmsis-dap JTAG TLR_RESET
    Info : cmsis-dap JTAG TLR_RESET
    Info : JTAG tap: riscv.cpu tap/device found: 0x1000563d (mfg: 0x31e (Andes Technology Corporation), part: 0x0005, ver: 0x1)
    Info : JTAG tap: auto0.tap tap/device found: 0x790007a3 (mfg: 0x3d1 (GigaDevice Semiconductor (Beijing)), part: 0x9000, ver: 0x7)
    Warn : AUTO auto0.tap - use "jtag newtap auto0 tap -irlen 5 -expected-id 0x790007a3"
    Info : datacount=4 progbufsize=2
    Info : Examined RISC-V core; found 1 harts
    Info :  hart 0: XLEN=32, misa=0x40901105
    Info : starting gdb server for riscv.cpu on 3333
    Info : Listening on port 3333 for gdb connections
    Info : cmsis-dap JTAG TLR_RESET
    Info : cmsis-dap JTAG TLR_RESET
    Info : cmsis-dap JTAG TLR_RESET
    Info : JTAG tap: riscv.cpu tap/device found: 0x1000563d (mfg: 0x31e (Andes Technology Corporation), part: 0x0005, ver: 0x1)
    Info : JTAG tap: auto0.tap tap/device found: 0x790007a3 (mfg: 0x3d1 (GigaDevice Semiconductor (Beijing)), part: 0x9000, ver: 0x7)
    Info : Listening on port 6666 for tcl connections
    Info : Listening on port 4444 for telnet connections
```

With the following content for `openocd_probe.cfg`:

```tcl
# openocd_probe.cfg
# =============
source [find interface/gdlink.cfg]
transport select jtag
```

And `openocd_chip.cfg`:

```tcl
# openocd_chip.cfg
# ============
adapter speed 1000
reset_config srst_only
adapter srst pulse_width 100
source [find target/gd32vf103.cfg]
```

Please note that the file `target/gd32vf103.cfg` is slightly modified (see my pull request https://github.com/GigaDevice-Semiconductor/openocd/pull/1).

Now I launch GDB in another console and try to connect it to OpenOCD:

```
$ riscv-none-embed-gdb
    riscv-none-embed-gdb: warning: Couldn't determine a path for the index cache directory.
    GNU gdb (xPack GNU RISC-V Embedded GCC, 64-bit) 8.3
    [...]
    (gdb) target extended-remote localhost:3333
    Remote debugging using localhost:3333
    bfd requires xlen 8, but target has xlen 4
```

The connection fails. In OpenOCD, I see this output:

```
Info : accepting 'gdb' connection on tcp/3333
Info : device id = 0x19060410
Info : flash size = 128kbytes
Info : dropped 'gdb' connection
```

OpenOCD drops the connection. I don't know why. It doesn't happen each time, but very often.

**Comment by kristofmulier** [comment]
I tried again with `version 0.10.0 dev00002` on Windows 10 and Ubuntu. The problem persists.

**Comment by GigaDevice-Semiconductor** [comment]
Please enter 

> set arch riscv:rv32

 in GDB before the 

> target extended-remote localhost:3333 

The problem can be solved effectively

**Comment by GigaDevice-Semiconductor** [comment]
> > Note: I've tried on both `Windows10` and `Ubuntu 20.04.1 LTS`. The errors described below are the same on both systems.
> 
> I'm trying to connect `riscv-none-embed-gdb` - which is part of the xPack RISC-V toolchain - to OpenOCD. For this test, I'm using the double-console-approach: I launch OpenOCD in one console and GDB in another.
> 
> This is how I launch OpenOCD such that it connects to the MCU on the `GD32VF103C-START` board:
> 
> ```
> $ openocd -f openocd_probe.cfg -f openocd_chip.cfg -c "init; reset halt;"
> 
>     xPack OpenOCD, x86_64 Open On-Chip Debugger 0.10.0+dev-00003-gfa63b9ee9 (2020-11-19-15:34)
>     Licensed under GNU GPL v2
>     For bug reports, read
>         http://openocd.org/doc/doxygen/bugs.html
>     jtag
>     Info : CMSIS-DAP: SWD  Supported
>     Info : CMSIS-DAP: JTAG Supported
>     Info : CMSIS-DAP: FW Version = 2.0.0
>     Info : CMSIS-DAP: Interface Initialised (JTAG)
>     Info : SWCLK/TCK = 1 SWDIO/TMS = 1 TDI = 1 TDO = 0 nTRST = 0 nRESET = 1
>     Info : CMSIS-DAP: Interface ready
>     Info : clock speed 1000 kHz
>     Info : cmsis-dap JTAG TLR_RESET
>     Info : cmsis-dap JTAG TLR_RESET
>     Info : JTAG tap: riscv.cpu tap/device found: 0x1000563d (mfg: 0x31e (Andes Technology Corporation), part: 0x0005, ver: 0x1)
>     Info : JTAG tap: auto0.tap tap/device found: 0x790007a3 (mfg: 0x3d1 (GigaDevice Semiconductor (Beijing)), part: 0x9000, ver: 0x7)
>     Warn : AUTO auto0.tap - use "jtag newtap auto0 tap -irlen 5 -expected-id 0x790007a3"
>     Info : datacount=4 progbufsize=2
>     Info : Examined RISC-V core; found 1 harts
>     Info :  hart 0: XLEN=32, misa=0x40901105
>     Info : starting gdb server for riscv.cpu on 3333
>     Info : Listening on port 3333 for gdb connections
>     Info : cmsis-dap JTAG TLR_RESET
>     Info : cmsis-dap JTAG TLR_RESET
>     Info : cmsis-dap JTAG TLR_RESET
>     Info : JTAG tap: riscv.cpu tap/device found: 0x1000563d (mfg: 0x31e (Andes Technology Corporation), part: 0x0005, ver: 0x1)
>     Info : JTAG tap: auto0.tap tap/device found: 0x790007a3 (mfg: 0x3d1 (GigaDevice Semiconductor (Beijing)), part: 0x9000, ver: 0x7)
>     Info : Listening on port 6666 for tcl connections
>     Info : Listening on port 4444 for telnet connections
> ```
> 
> With the following content for `openocd_probe.cfg`:
> 
> ```tcl
> # openocd_probe.cfg
> # =============
> source [find interface/gdlink.cfg]
> transport select jtag
> ```
> 
> And `openocd_chip.cfg`:
> 
> ```tcl
> # openocd_chip.cfg
> # ============
> adapter speed 1000
> reset_config srst_only
> adapter srst pulse_width 100
> source [find target/gd32vf103.cfg]
> ```
> 
> Please note that the file `target/gd32vf103.cfg` is slightly modified (see my pull request #1).
> 
> Now I launch GDB in another console and try to connect it to OpenOCD:
> 
> ```
> $ riscv-none-embed-gdb
>     riscv-none-embed-gdb: warning: Couldn't determine a path for the index cache directory.
>     GNU gdb (xPack GNU RISC-V Embedded GCC, 64-bit) 8.3
>     [...]
>     (gdb) target extended-remote localhost:3333
>     Remote debugging using localhost:3333
>     bfd requires xlen 8, but target has xlen 4
> ```
> 
> The connection fails. In OpenOCD, I see this output:
> 
> ```
> Info : accepting 'gdb' connection on tcp/3333
> Info : device id = 0x19060410
> Info : flash size = 128kbytes
> Info : dropped 'gdb' connection
> ```
> 
> OpenOCD drops the connection. I don't know why. It doesn't happen each time, but very often.
